### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by calimansi** [Bepacom-Raalte/bepacom-HA-Addons#18]
I copied the repo into customer_components.
Tried to search for BACnet in Settings -> Devices & Services -> + Add Integration.  BACnet does not show up.
Tried restarting Home Assistant the integration still doesn't show up.

Not sure what else to do.

**Comment by calimansi** [comment]
Nevermind... you changed the method to install..

**Comment by calimansi** [comment]
Please close.  I see you added a link to add the repo directly.

**Comment by Bepacom-Raalte** [comment]
Of course! Let me know if there are any more issues.
