### ISSUE TITLE
The entity does not consider the Resolution of a BACnet object

### ISSUE THREAD

**Issue by CV-Private** [Bepacom-Raalte/bepacom-HA-Addons#46]
The automatically generated Entity does not consider the Resolution of a BACnet object.

Here's an example with my GTW-21 device: Analog Value AV1673 _parZoneMode-3_ is a Mode switch that has only three valid states: 0, 1 and 2. This is reflected in the object properties Min Pres Value 0, Max Pres Value 2, **Resolution 1**, as can be seen in Yabe:

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/f4875a7c-a1de-4b5e-b4f9-f2be7b0103f1)

The automatically generated Entity, however, allows to increment the value in 0.1 steps:

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/2179e2b2-8934-4354-a894-4853a22230f3)

It seems that the BACnet device rejects that invalid write command - that would at least be my understanding of the orange bullet in the log. Setting the property to a valid value returns a blue bullet in the log:

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/53b850cd-479d-42f4-b7c8-1b229ecece98)

Despite the rejection of the first command, the Entity was displaying the value as 1.1 without showing any error.

**Comment by GravySeal** [comment]
You're right about resolution, I'll include it in the next add-on release. After that, it'll be added to the integration.

**Comment by gioassio89** [comment]
Hi,
seems that there is some in the definition of the resolution for analog writable:

![Senzanome](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/166951559/e93c9f89-55c3-42aa-bd3a-5b843b8088bf)

![test](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/166951559/5739737c-c550-4327-8642-b2f80f4cab23)

**Comment by GravySeal** [comment]
The integration looks whether resolution exists, if it doesn't it checks of CoV increment exists, and if neither are there it'll use a resolution of 1. Maybe it's missing those BACnet properties?

**Comment by CV-Private** [comment]
The resolution is now being considered in v1.4.1b6 and works fine with the GTW-21. For example, the AV1673 value is now changing in integer steps when I click the up/down buttons.

Would be great, though, if the Integration would also adjust the decimal places according to the resolution. Currently, the AV1673 value is shown as 1.0 in the Dashboard, even though the resolution is 1. Could it be shown as an integer number instead?

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/dd278839-8d2f-40e7-8304-ea1e2d2161b7)

**Comment by Bepacom-Raalte** [comment]
Could you try v0.2.1b3? Should be fixed in this version. It'll check based on the step, which is based on resolution or CoV increment. When the resolution is one or greater, the value will be integer instead of floating point.

**Comment by CV-Private** [comment]
With v0.2.1b3, I do see progress in the editable fields.

However, in the non-editable sensor readings (sorry - I don't have a better name for that), the decimal places are not yet corresponding to the resolution of the object, which I read out with Yabe:

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/3c059d33-4969-4550-954a-8474f65757ee)

**Comment by Bepacom-Raalte** [comment]
Right, sensor is different from number. I've changed the sensor to be rounded based on resolution or CoV increment in v0.2.1b4. Please try it.

**Comment by CV-Private** [comment]
Great, works fine in v0.2.1b4, also with AI460 that has a resolution of 0.001:

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/fd39ee08-cd4d-48db-b2d5-5fdbd8798653)

**Comment by Bepacom-Raalte** [comment]
I think this would be something Home Assistant related. If all the other decimals are corresponding to their resolution or CoV increment, then it's something out of our control.

**Comment by CV-Private** [comment]
Works fine now. Thanks! :-)
