### ISSUE TITLE
Request to add units

### ISSUE THREAD

**Issue by SQ9MDD** [Bepacom-Raalte/bepacom-HA-Addons#49]
I want to transfer some readings from homeassistant to bacnet. 
I am missing units:

µg/m³ for air quality parameters,
m³ for water consumption measurements

Thanks a lot.

**Comment by GravySeal** [comment]
Sure thing, I'll add them next beta!

**Comment by gioassio89** [comment]
Hi,
seems miss also energy units: kWh
time units: s min h, 
this integration is fantastic! 
Thanks a lot!

**Comment by SQ9MDD** [comment]
kWh is ok, also Celsius, lx, V, W, we are waiting for the rest of them, check this out:

@GravySeal any plans for update ?

![Przechwytywanie](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/5675191/f031b3e5-24d0-40c8-b4a2-6f492c9551bc)

**Comment by Bepacom-Raalte** [comment]
Hello,

I'll add seconds, minutes and hours as engineering units as well. I'd been hoping on a little more feedback for the beta, as there's quite a few changes to the inner workings. I think I'll push update 1.4.1b6 tonight including the units added.

**Comment by gioassio89** [comment]
Hi,
HA side i cannot see points that have W KWh dont have untits:
![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/166951559/5727902b-a8ee-4328-a183-0dbcac0cf28d)
But the device that export point have it, % °C have no problem:
![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/166951559/f3080d49-ddaf-4a6c-84ee-a4fef54cb192)
I do something wrong?

**Comment by Bepacom-Raalte** [comment]
This is from a BACnet device to Home Assistant, right? Currently the integration supports only 3 units, so this is an integration issue and not the add-on. If you have a list of units you want supported in Home Assistant, you can make an issue on the [integration GitHub page](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/issues) so I can add them there.

**Comment by gioassio89** [comment]
sorry i will make an issue in the correct place! thanks a lot!
