### ISSUE TITLE
The Add-On did not restore the previous operating state after the BACnet device was power-cycled. 

### ISSUE THREAD

**Issue by CV-Private** [Bepacom-Raalte/bepacom-HA-Addons#50]
I had to turn the GTW-21 off and on, and I found that the Add-On did not re-subscribe to CoV after the BACnet device was power-cycled. 

CoV subscriptions and polling were active before the power-cycle, but not thereafter. I see in Yabe that there are no active subscriptions, even though the Add-On has subscriptions in the list.

I'd propose to add a recovery mechanism that restores the previous operating state if the connections to the BACnet device was interrupted.

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/13fde4b8-c957-4158-a3de-41894a34a825)

**Comment by GravySeal** [comment]
There's plans to make some sort of a heartbeat functionality to poll whether a device is still there, but for now it doesn't have a priority.
A way to work around this issue is having the CoV heartbeat shorter, like 120 seconds for example. This is a similar way to how Yabe does it.

**Comment by CV-Private** [comment]
Hmm.. can I configure the heartbeat in the current Add-On? I didn't find anything in your documentation about that option...

**Comment by Bepacom-Raalte** [comment]
There currently is no heartbeat, just something I want to implement later.

As for resubscribing, restarting Home Assistant does nothing to the add-on. Only rebooting the host device will also restart the add-on. Instead, you can decrease the lifetime of a CoV subscription from 28800 to 120 seconds. This should resubscribe. If it doesn't, feel free to leave some logs so I can take a look at what's happening.

**Comment by GravySeal** [comment]
The add-on should now restore CoV subscriptions after the device lost connection. This will be done through resubscribing when the lifetime of the subscription has passed.
