### ISSUE TITLE
No CoV re-subscription after the connection to the BACnet device was interrupted

### ISSUE THREAD

**Issue by CV-Private** [Bepacom-Raalte/bepacom-HA-Addons#52]
After I disconnected and re-connected the GTW-21 from the network, the previously active CoV subscriptions were not re-established. 

Only the Quick-Poll values are being updated in the Integration, but there's no more update of the CoV values since the network connection was down, which is meanwhile more than two hours ago:

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/c17c496f-894f-43a6-8131-343fbe147e5f)

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/b7ece1f4-8842-455a-a8a6-7f1cd881b183)

I think this was already described as part of another issue, but hasn't been addressed yet, therefore I'm opening it as a new report.

**Comment by GravySeal** [comment]
Yes, thank you for making this a separate issue. Once I have more time I'll look into a solution for this problem. I've been testing around a little bit but unfortunately haven't found an easy fix yet.

**Comment by GravySeal** [comment]
In v1.5.1b1 it should resubscribe now after the CoV lifetime has passed.
