### ISSUE TITLE
Large Installation

### ISSUE THREAD

**Issue by BertPorter** [Bepacom-Raalte/bepacom-HA-Addons#53]
I am managing 14 BACnet devices using a ComfortClick server. The devices are BASControl22 and BASControl22c by Contemporary Controls. I would like to migrate to HomeAssistant using your integration. Initially I am using a trial HA installation so I don't endanger my live system which primarily uses Z-Wave devices. 

I assume I will have a lot of feedback/questions for you. Is this the best place to post them?

Thanks.

**Comment by GravySeal** [comment]
Hey BertPorter,

This place is fine to put questions and feedback. Opening a discussion is fine too, so feel free to choose whatever is your preference.
