### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BertPorter** [Bepacom-Raalte/bepacom-HA-Addons#55]
I appreciate that you are doing this integration. I've been waiting for it for a couple years. I understand it will take awhile to get all needed features.

1. I changed the names of some inputs/outputs on a BACnet device and they didn't update in your Addon. Any suggestions? 

2. Do you plan to provide control over individual devices, such as the ability to pull in a device by its Device ID or IP address? And the ability to remove a specific device from the list of found devices? And the ability to remove specific fields from a device. Often many of the inputs/outputs aren't being used.

3. Do you plan to provide any documentation for the Addon Web UI.

Thank you

**Comment by GravySeal** [comment]
Hello,

1.  The add-on basically only reads the name of a property once, which is after it received the I Am request. After that it'll only read presentValue, statusFlags, outOfService, eventState, reliability and covIncrement. Right now the only way to get the updated object name is to write that property in the add-on web UI or to restart the add-on.
2. In the latest dev version, I'm experimenting with setting up devices in a more customized way. I won't support setting up by IP soon, but in the dev version you can use custom settings per device, like having a manual selection of objects you want CoV on, a list of objects that would need fast polling and a list for slow polling. Of course this functionality can still be expanded, like having it ignore certain device ID's all together.
3. I am hoping to overhaul the web UI to be more coherent and a bit more professional looking when I have the time. I did include some tooltips when hovering over buttons in the UI to hopefully give the user an idea of what the button does. I think it's useful to write documentation for the UI when it's overhauled.
