### ISSUE TITLE
Statistics for orphaned entities in my HA, saying the entity has no status

### ISSUE THREAD

**Issue by CV-Private** [Bepacom-Raalte/bepacom-HA-Addons#56]
I found this warning in the Debug log of my Integration: "_2024-04-22 01:50:10.099 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.gtw_21_bacnet_783351856_varapactualproducerpower (kW) cannot be converted to the unit of previously compiled statistics (None). Generation of long term statistics will be suppressed unless the unit changes back to None or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this_"

I guess the unit had been changed during some recent update of the Integration?

Opening the above mentioned link unveiled another issue. There's a big number of orphaned entities in my HA, saying the entity has no status, and the developer page asks me if I want to delete the long-term statistics for those. 
I guess I should do that, but it's quite tedious, because I can only fix it line-by-line for >200 entities...

![image](https://github.com/Bepacom-Raalte/bepacom-HA-Addons/assets/108861703/7ef34537-aa69-4860-bb8e-f408cbd62664)

**Comment by GravySeal** [comment]
Right, the units have been changed as now BACnet engineering units get translated to their corresponding Home Assistant units. I didn't know this would happen, so it's a little unfortunate. Might put out a warning for users who want to update their integration then.
