### ISSUE TITLE
Update the list of bacnet point in a device

### ISSUE THREAD

**Issue by gioassio89** [Bepacom-Raalte/bepacom-HA-Addons#57]
Hello,
 I have encountered this issue. If I add a new BACnet point to a device already integrated into HA, the only way I found to display it is: 
1. reload the add-on, 
3. Remove the device from the integration, 
4. 3. Reload the integration. 
I think the issue for the add-on is that every time I update the configuration of my BACnet device, the add-on continues to assume that the old objects are still present. It does not check for the new objects, so it will never update to the new configuration.

thanks

**Comment by GravySeal** [comment]
In v1.5.1b2, the add-on reads the object list again (if the option is configured) once the device sends out an I-Am request. If the object list is different, the add-on should read all objects again.
